package com.mehdik.mvvmdi.entities

data class TagListEntity(
    val alternative_name_hp: Any,
    val alternative_name_rp: Any,
    val alternative_name_srp: Any,
    val alternative_names: Any,
    val banner_web: String,
    val display_order: Int,
    val id_city_indexable: Any,
    val id_country_restriction: Any,
    val id_restaurant_tag: Int,
    val id_restaurant_tag_category: Int,
    val id_restaurant_tag_level_1: Any,
    val id_restaurant_tag_level_2: Any,
    val id_restaurant_tag_substitute: Any,
    val indexable: Int,
    val is_deleted: Int,
    val is_displayed_search: Boolean,
    val is_published_portal: Boolean,
    val marketing_banner: String,
    val marketing_description: Any,
    val marketing_title: Any,
    val pic_large: String,
    val pic_mobile: String,
    val pic_small: String,
    val search_volume: Int,
    val seo_desc: Any,
    val seo_h1: Any,
    val seo_title: Any,
    val slug_indexable: String,
    val slug_list: List<Any>,
    val tag_description: String,
    val tag_name: String,
    val title: Any
)